ARG node_version=18
ARG node_image=node:${node_version}

FROM $node_image AS dev

COPY . /app/
ENV NODE_ENV=development

WORKDIR /app/backend
RUN yarn --network-timeout 300000

WORKDIR /app
RUN yarn --network-timeout 300000

ENTRYPOINT /app/docker-entrypoint-dev.sh

# run with docker run --rm -ti -p 3000:3000 -v $PWD/.env:/app/.env:ro your-image-name
